# Generated by Django 6.0.3 on 2026-03-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=50)),
                ('complaint_text', models.TextField()),
                ('translated_text', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
            ],
        ),
    ]
